czcorpus/wag

- package.json
- src/css/index.less
- src/js/abstract/types.ts
- src/js/index.ts
- src/js/models/actions.ts
- src/js/models/main.ts
- src/js/notifications.ts
- src/js/shared/data.ts
- src/js/tiles/concordance/index.ts
- src/js/tiles/concordance/model.ts
- src/js/tiles/ttDistrib/index.ts
- src/js/views/main.tsx
- src/translations/messages.json
- better form validation and status notification
- model dependencies improved
> Several improvements

- webpack.prod.js
(TODO - remove redundant stuff and use merge)
> Add webpack.prod config (initial)

- webpack.prod.js
(still needs e.g. JS minification)
> Fix production mode

- src/js/index.ts
(this helps e.g. when Android's software keyboard
is shown)
> Do not fire redraw in case form is active

- src/js/abstract/types.ts
- src/js/index.ts
- src/js/models/actions.ts
- src/js/shared/api/concordance.ts
- src/js/shared/api/kontextFreqs.ts
- src/js/tiles/collocations/index.ts
- src/js/tiles/collocations/views.tsx
- src/js/tiles/concordance/views.tsx
- src/js/tiles/freqPie/index.ts
- src/js/tiles/freqPie/view.tsx
- src/js/tiles/mergeCorpFreq/actions.ts
- src/js/tiles/mergeCorpFreq/index.ts
- src/js/tiles/mergeCorpFreq/messages.json
- src/js/tiles/mergeCorpFreq/model.ts
- src/js/tiles/mergeCorpFreq/style.less
- src/js/tiles/mergeCorpFreq/view.tsx
- src/js/tiles/summary/index.ts
- src/js/tiles/summary/view.tsx
- src/js/tiles/syd/index.ts
- src/js/tiles/syd/view.tsx
- src/js/tiles/timeDistrib/index.ts
- src/js/tiles/timeDistrib/view.tsx
- src/js/tiles/treq/view.tsx
- src/js/views/global.tsx
... plus several required changes
> Implement a new tile - mergeCorpFreq

- package.json
- src/js/common/conf.ts
- src/js/index.ts
- src/js/models/actions.ts
- src/js/models/query.ts
- src/js/models/tiles.ts
- src/js/server/core.ts
- src/js/server/routes.ts
- src/js/views/corpusInfo.tsx
- src/js/views/layout.tsx
- src/js/views/main.tsx
- first page input form with validation
(can be replaced by some external host page/app)
- second page - result
(can be referred via a URL)
> Modify app to work as two-page one

- src/js/common/api/concordance.ts
- src/js/common/models/concordance.ts
- src/js/tiles/concordance/index.ts
- src/js/tiles/concordance/style.less
- src/js/tiles/concordance/views.tsx
- src/js/tiles/timeDistrib/model.ts
(as a part of the existing conc tile)
> Parallel concordance

- src/js/index.ts
- src/js/layout.ts
- src/js/tiles/empty.ts
> Use EmptyTile to keep tileId=>idx mapping consistent

- src/css/components/main.less
- src/js/appServices.ts
- src/js/common/api/kontext/concordance.ts
- src/js/common/api/kontext/posQuery.ts
- src/js/common/models/concordance.ts
- src/js/common/types.ts
- src/js/conf.ts
- src/js/index.ts
- src/js/models/actions.ts
- src/js/models/query.ts
- src/js/server/actionServices.ts
- src/js/server/freqdb/common.ts
- src/js/server/freqdb/freqdb.ts
- src/js/server/routes.ts
- src/js/tiles/concordance/index.ts
- src/js/tiles/concordance/model.ts
- src/js/tiles/mergeCorpFreq/model.ts
- src/js/tiles/similarFreqs/api.ts
- src/js/tiles/similarFreqs/model.ts
- src/js/tiles/timeDistrib/index.ts
- src/js/tiles/timeDistrib/model.ts
- src/js/tiles/wordFreq/model.ts
- src/js/views/layout.tsx
- src/js/views/main.tsx
- src/translations/messages.json
i.e. always consider word+lemma+pos and display tiles
only for the single variant (if possible)
> Search according to one of pre-searched lemma variants

- src/js/common/api/kontext/concordance.ts
- src/js/conf.ts
- src/js/index.ts
- src/js/tiles/collocations/common.ts
- src/js/tiles/collocations/index.ts
- src/js/tiles/collocations/model.ts
- src/js/tiles/concFilter/actions.ts
- src/js/tiles/concFilter/index.ts
- src/js/tiles/concFilter/message.json
- src/js/tiles/concFilter/model.ts
- src/js/tiles/concFilter/style.less
- src/js/tiles/concFilter/view.tsx
- src/js/tiles/concordance/actions.ts
used e.g. to provide collocations example
> New tile - conc filter

- src/js/models/actions.ts
- src/js/tiles/collocations/views.tsx
- src/js/tiles/concFilter/model.ts
(this e.g. allows conc. filter tile to synchronize itself with
collocation tile)
> Synchronize coll context change and subq. actions

- src/js/index.ts
- src/js/models/actions.ts
- src/js/models/query.ts
- src/js/models/tiles.ts
- go directly to answer page on query type change (if possible)
> Improve main menu behavior

- package-lock.json
> Add package-lock to the project

- src/js/app.ts
- src/js/common/query.ts
- src/js/layout.ts
- src/js/models/query.ts
- src/js/views/main.tsx
(i.e. we now show only stuff the layout is configured for)
> Base query type menu on actual configuration

- src/css/components/main.less
> Fix z-index of modal box

- src/js/conf.ts
- src/js/index.ts
- src/js/server/routes.ts
(not very elegant solution but a working one)
> Allow toolbar initialization

- package-lock.json
- src/js/appServices.ts
- src/js/common/api/abstract/wordForms.ts
- src/js/common/api/kontext/concordance.ts
- src/js/common/query.ts
- src/js/conf.ts
- src/js/models/actions.ts
- src/js/models/query.ts
- src/js/server/freqdb/freqdb.ts
- src/js/server/logging/abstract.ts
- src/js/server/routes.ts
- src/js/tiles/wordForms/model.ts
- src/js/tiles/wordFreq/api.ts
- src/js/tiles/wordFreq/model.ts
- src/js/tiles/wordFreq/views/chart.tsx
- src/js/tiles/wordFreq/views/index.tsx
- src/js/views/main.tsx
- src/translations/messages.json
(quite a huge change; should be tested)
> multi-value PoS lemma variants

- src/js/common/query.ts
- src/js/server/routes.ts
... when defining items order (problem of positioning
of merged items).
> lemma variants - add some intelligence

- src/js/common/models/concordance/normalize.ts
- src/js/tiles/speeches/api.ts
- src/js/tiles/speeches/model.ts
- src/js/tiles/speeches/modelDomain.ts
- src/js/tiles/speeches/view.tsx
... to allow normalizing of kwic details/speeches too
> Generalize typography normalizer

- src/js/common/api/abstract/concordance.ts
- src/js/common/api/abstract/switchMainCorp.ts
- src/js/common/api/kontext/concordance.ts
- src/js/common/api/kontext/switchMainCorp.ts
- src/js/tiles/concFilter/index.ts
- src/js/tiles/concFilter/model.ts
- src/js/tiles/concFilter/style.less
- src/js/tiles/concFilter/view.tsx
- src/js/tiles/wordForms/model.ts
i.e. now we can not only search for subquery based collocations
but also for specific translations
> ConcFilter tile - add support for aligned corpora

- src/js/app.ts
- src/js/common/query.ts
- src/js/common/types.ts
- src/js/conf.ts
- src/js/models/query.ts
- src/js/server/routes.ts
- src/js/views/main.tsx
- show only search languages available for the current setup
- refactor stuff sligthly
> Search lang improvements

- conf/wdglance.sample.json
- src/js/appServices.ts
- src/js/conf.ts
- src/js/index.ts
- src/js/layout.ts
- src/js/models/query.ts
- src/js/server/routes.ts
- src/js/tiles/timeDistrib/model.ts
- src/js/tiles/treq/model.ts
- src/js/tiles/wordForms/model.ts
- src/js/tiles/wordFreq/model.ts
- src/js/views/main.tsx
the change requires update in layouts conf
> Rewrite target language config and application

- src/js/common/api/abstract/collocations.ts
- src/js/common/api/kontext/concordance.ts
- src/js/common/query.ts
- src/js/tiles/collocations/common.ts
- src/js/tiles/collocations/model.ts
- src/js/tiles/concFilter/model.ts
... the previous version has been ignoring left/right/both context
> Fix collocation examples

- src/js/common/models/treq.ts
- src/js/tiles/treq/index.ts
- src/js/tiles/treq/model.ts
- src/js/tiles/treqSubsets/actions.ts
- src/js/tiles/treqSubsets/index.ts
- src/js/tiles/treqSubsets/model.ts
- src/js/tiles/treqSubsets/view.tsx
- also fix flipped table columns
> Treq min freq

- src/js/common/api/abstract/collocations.ts
- src/js/common/api/kontext/collocations.ts
- src/js/common/api/lcc/cooccurrences.ts
- src/js/tiles/collocations/apiFactory.ts
- src/js/tiles/collocations/index.ts
- src/js/tiles/collocations/model.ts
> Add API for cooccurrences provided by the  Leipzig Corpora Collection

- src/js/server/routes.ts
> Fixed usage of deprecated redirect

- src/js/tiles/core/freqComparison/model.ts
... as there can be multiple instances of the tile installed
> Bugfix - test tileId even for actions specific for this tile

- src/js/common/api/kontext/freqTree.ts
- src/js/common/models/freqTree.ts
- src/js/tiles/core/freqTree/actions.ts
- src/js/tiles/core/freqTree/index.ts
- src/js/tiles/core/freqTree/messages.json
- src/js/tiles/core/freqTree/model.ts
- src/js/tiles/core/freqTree/style.less
- src/js/tiles/core/freqTree/view.tsx
Example tile settings:
```
"TreeComparison": {
"tileType": "FreqTreeTile",
"apiURL": "/kontext",
"corpname": "syn2015",
"fcritTrees": [
["doc.txtype_group 0", "doc.genre_group 0"],
["doc.genre_group 0", "doc.genre 0"]
],
"treeLabels": [
{
"cs-CZ": "Textová skupina x žánrová skupina",
"en-US": "Text type group x genre group"
},
{
"cs-CZ": "Textová skupina x žánrová skupina",
"en-US": "Text type group x genre group"
}
],
"flimit": 1,
"fpage": 1,
"fttIncludeEmpty": false,
"maxChartsPerLine": 2,
"colors": [
"#8addff",
"#f26e43",
"#70b3cf",
"#3a78eb"
]
}
```
> Basic frequency tree tile

- src/js/tiles/core/multiWordTimeDistrib/apiFactory.ts
- src/js/tiles/core/multiWordTimeDistrib/common.ts
- src/js/tiles/core/multiWordTimeDistrib/index.ts
- src/js/tiles/core/multiWordTimeDistrib/messages.json
- src/js/tiles/core/multiWordTimeDistrib/model.ts
- src/js/tiles/core/multiWordTimeDistrib/stat.ts
- src/js/tiles/core/multiWordTimeDistrib/style.less
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
Example config:
```
"MultiWordTimeDistLemmaSynchronic": {
"tileType": "MultiWordTimeDistribTile",
"apiType": "kontext",
"apiURL": "/kontext",
"concApiURL": "/kontext",
"concMaxSize": 10000,
"corpname": "syn2015",
"fcrit": "doc.pubyear 0",
"flimit": 1,
"posQueryGenerator": [
"tag",
"ppTagset"
]
},
```
> Multi word time distribution tile

- conf/layouts-schema.json
- conf/server-schema.json
- conf/tiles-schema.json
- conf/wdglance-schema.json
- src/js/appServices.ts
- src/js/conf.ts
- src/js/server/actionServices.ts
- src/js/server/freqdb/freqdb.ts
- src/js/tiles/core/wordFreq/api.ts
- src/js/tiles/core/wordFreq/index.ts
- src/js/tiles/core/wordFreq/model.ts
- src/js/tiles/core/wordFreq/views/common.tsx
- src/js/tiles/core/wordFreq/views/index.tsx
- src/js/tiles/core/wordFreq/views/single.tsx
Please update your *server.json* conf:
From this:
```json
"cs": {
"/var/www/korpus/wdglance/syn2015-arf.v3.db"
},
"en": {
"/var/www/korpus/wdglance/intercorp_v11_wdg.db"
}
```
to this:
```json
"cs": {
"path": "/var/www/korpus/wdglance/syn2015-arf.v3.db",
"corpusSize": 120748715
},
"en": {
"path": "/var/www/korpus/wdglance/intercorp_v11_wdg.db",
"corpusSize": 248083837
}
```
> Word profile - preparing for multi-word variant

- src/js/tiles/core/html/index.ts
- src/js/tiles/core/html/messages.json
- src/js/tiles/core/html/model.ts
- src/js/tiles/core/html/service.ts
- src/js/tiles/core/html/views.tsx
- added "not found" message to wiktionary api
- using addActionHandler in html tile model
> Html tile handling 404

- src/js/tiles/core/multiWordGeoAreas/model.ts
(cannot use combineLatest as the map can be loaded
last in which case only the last of the freq. results is used)
> Fix streams combination

- src/js/tiles/core/geoAreas/index.ts
- src/js/tiles/core/geoAreas/messages.json
- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/tiles/core/multiWordGeoAreas/messages.json
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- adds tooltip message `not enough data` for multiWordGeoAreas tile
- adds `frequencyDisplayLimit` settings and `not enough data` tooltip message to geoAreas tile
- improves displaying tooltips in multiWordGeoAreas tile on mouse over
> Not enough data message for geo tiles

- package.json
- src/js/conf.ts
- src/js/server/routes.ts
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
Setting log file in `conf/server.json` for example like this:
```
"logging": {
"path": "/var/log/wdglance/application-%DATE%.log",
"rotation": true
}
```
> Added winston logger to wdgRouter

- src/js/views/main.tsx
> Fixed query field focus on cmp mode switch

- src/js/tiles/core/freqComparison/view.tsx
> freqComparison bar with separators

- src/js/common/api/kontext/concordance.ts
- src/js/tiles/core/concFilter/model.ts
> Escaping " in `mkContextFilter` function

- src/js/tiles/core/multiWordTimeDistrib/view.tsx
> Resizing multiword time distrib y domain for % unit

- src/js/tiles/core/freqBar/view.tsx
- src/js/tiles/core/freqComparison/view.tsx
- src/js/tiles/core/freqTree/view.tsx
- src/js/tiles/core/mergeCorpFreq/view.tsx
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
- src/js/tiles/core/timeDistrib/view.tsx
- src/js/views/global.tsx
> added custom recharts tooltip to global components

- src/js/tiles/core/multiWordTimeDistrib/apiFactory.ts
- src/js/tiles/core/multiWordTimeDistrib/common.ts
- src/js/tiles/core/multiWordTimeDistrib/index.ts
- src/js/tiles/core/multiWordTimeDistrib/model.ts
- src/js/tiles/core/timeDistrib/apiFactory.ts
- src/js/tiles/core/timeDistrib/common.ts
- src/js/tiles/core/timeDistrib/index.ts
- src/js/tiles/core/timeDistrib/model.ts
> Multiple sources for chunk load

- src/js/tiles/core/multiWordTimeDistrib/model.ts
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
> Fix - Test tileId

- package-lock.json
- package.json
- src/js/common/priority.ts
- src/js/tiles/core/multiWordTimeDistrib/common.ts
- src/js/tiles/core/multiWordTimeDistrib/index.ts
- src/js/tiles/core/multiWordTimeDistrib/model.ts
(we can set a probability a concrete api will be selected)
> Multiple APIs with priorities

- src/js/tiles/core/multiWordTimeDistrib/model.ts
- src/js/tiles/core/timeDistrib/model.ts
(we need a new instance from pool for each queryMatch X dataChunk)
> Fix api instance scope

- INSTALL.md
> Updated INSTALL.md to accomodate new script method

- README.md
- src/js/common/api/abstract/freqs.ts
- src/js/common/api/factory/freqs.ts
- src/js/common/api/kontext/freqs.ts
- src/js/common/api/noske/collocations.ts
- src/js/common/api/noske/freqs.ts
- src/js/common/models/freq.ts
- src/js/tiles/core/freqBar/model.ts
- src/js/tiles/core/freqBar/subqModel.ts
- src/js/tiles/core/freqComparison/index.ts
- src/js/tiles/core/freqComparison/model.ts
- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/mergeCorpFreq/model.ts
- src/js/tiles/core/multiWordGeoAreas/index.ts
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/timeDistrib/index.ts
> Noske freq api

- README.md
- src/js/common/api/abstract/freqs.ts
- src/js/common/api/kontext/freqs.ts
- src/js/common/api/noske/concordance.ts
- src/js/common/api/noske/freqs.ts
- src/js/common/models/freq.ts
- src/js/common/models/freqComparison.ts
- src/js/tiles/core/freqComparison/model.ts
- src/js/tiles/core/mergeCorpFreq/model.ts
- src/js/tiles/core/multiWordGeoAreas/model.ts
> NoSke support for MergeCorpFreq tile and FreqComparison tile

- src/js/common/api/abstract/timeDistrib.ts
- src/js/common/api/kontext/timeDistrib.ts
- src/js/common/api/noske/timeDistrib.ts
- src/js/tiles/core/timeDistrib/model.ts
Now it supports both kontext and noske
> Fixed timeDistribAPI backlinks

- src/js/tiles/core/colloc/views.tsx
- src/js/tiles/core/translations/view.tsx
- src/js/tiles/core/wordForms/views.tsx
- src/js/tiles/core/wordSim/view.tsx
- src/js/views/wordCloud/index.tsx
> Removed word cloud inline styling

- conf/server-schema.json
- conf/wdglance-schema.json
- src/js/conf/index.ts
- src/js/conf/validation.ts
- src/js/server/index.ts
- src/js/server/routes/main.ts
> Tiles config logic improved

- assets/mapCzech.inline.svg
- src/js/tiles/core/multiWordGeoAreas/messages.json
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/style.less
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/views/global.tsx
> Multi geo areas visual improvements

- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/style.less
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- tweaked pie and tooltip shadows
- tooltip percents with one decimal place
- displayed numbers have locale formatting
> Multi geo areas improve

- src/js/server/actionServices.ts
- src/js/server/index.ts
- src/js/server/logging/redisQueue.ts
- src/js/server/queryLog/abstract.ts
- src/js/server/queryLog/nullQueue.ts
- src/js/server/queryLog/redisQueue.ts
- src/js/server/routes/common.ts
- src/js/server/routes/main.ts
- webpack.prod.js
> Log queue refactor

- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/style.less
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- increased tooltip bottom border
- aligning tooltip data by decimal separator
Issue #690
> Multi word geo tooltip fix

- assets/mapCzech.inline.svg
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/tiles/core/multiWordTimeDistrib/messages.json
- src/js/tiles/core/multiWordTimeDistrib/style.less
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
- src/js/tiles/core/wordFreq/views/compare.tsx
Improved multiWordTimeDistrib tile
- tooltip
- legend
+ fixed legend holder in czech svg map
Issue #691
> Multi word time distrib tooltip improvements

- src/js/tiles/core/wordFreq/views/single.tsx
> Displaying pos when multiple same words with similar frequency

- src/js/tiles/core/wordFreq/actions.ts
- src/js/tiles/core/wordFreq/index.ts
- src/js/tiles/core/wordFreq/model.ts
- src/js/tiles/core/wordFreq/views/index.tsx
- src/js/tiles/core/wordFreq/views/single.tsx
> Word freq full PoS names on mouseover

- src/css/index.less
- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/views/global.tsx
> Geo area improvements

- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/tiles/core/multiWordTimeDistrib/style.less
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
- smaller geo map pie shadows
- multiWordTimeDistrib visual fixes
> Visual fixes

- src/js/views/wordCloud/index.tsx
> Fixed wordCloud tooltip layout

- src/js/views/global.tsx
> Improved AlignedRechartsTooltip styling

- src/js/tiles/core/concordance/style.less
- src/js/tiles/core/freqBar/style.less
- src/js/tiles/core/freqComparison/style.less
- src/js/tiles/core/freqPie/style.less
> Charts with multiple blocks aligned on the bottom

- src/js/models/query.ts
- src/js/server/routes/actions.ts
- src/js/server/routes/common.ts
- src/js/server/routes/index.ts
- src/js/server/routes/main.ts
> Pretty query url

- launcher-config.json
> Running tests before building server and production

- launcher-config.json
- launcher-menu.json
- scripts/create-tile.ts
- scripts/template-tile/common.ts
- scripts/template-tile/config-schema.json
- scripts/template-tile/index.ts
- scripts/template-tile/messages.json
- scripts/template-tile/model.ts
- scripts/template-tile/style.less
- scripts/template-tile/views.tsx
Running `npm start create:custom-tile <tile_name>` will create new custom tile
Part of #375
> Basic create custom tile template and script

- src/js/common/api/treq/index.ts
> Implemented treq n-gram support

- src/js/common/api/factory/translations.ts
- src/js/tiles/core/translations/index.ts
> Translations api factory moved to common/api/factory dir

- src/js/tiles/core/wordSim/view.tsx
> WordSim - using correct colors in cmp mode

- src/js/tiles/core/mergeCorpFreq/view.tsx
> Allowing tooltip to show over y-axis

- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/tiles/core/mergeCorpFreq/actions.ts
- src/js/tiles/core/mergeCorpFreq/index.ts
- src/js/tiles/core/mergeCorpFreq/model.ts
- src/js/tiles/core/mergeCorpFreq/view.tsx
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/tiles/core/treqSubsets/view.tsx
- src/js/views/global.tsx
- MergeCorp freq tile uses ElementTooltip - issue #739 
- MultiWordGeo tile uses ElementTooltip
> Tooltip improvements

- src/js/tiles/core/multiWordTimeDistrib/view.tsx
Could not find any example to test it, hope this works...
Issue #801
> Using formatNumber in multiWordTimeDistrib tick formatter

- src/js/views/global.tsx
> Fixed error complaining about react element unique key

- src/js/tiles/core/freqComparison/style.less
- src/js/tiles/core/freqComparison/view.tsx
> freqComparison tile - overflowing tables can be scrolled

- package.json
- src/js/server/index.ts
> Using session file store

- conf/server-schema.json
- launcher-menu.json
- src/js/conf/index.ts
- src/js/server/index.ts
> Added session to server config

- .gitignore
- dist/.compiled/.gitignore
- dist/.gitignore
> Making sure dist and dist/.compiled dirs are ready fresh from git

- src/js/tiles/core/geoAreas/actions.ts
- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
> Geo areas show insufficient data correctly

- conf/themes.json
- package.json
- src/js/page/theme.ts
- src/js/tiles/core/colloc/views.tsx
- src/js/tiles/core/freqComparison/view.tsx
- src/js/tiles/core/mergeCorpFreq/view.tsx
- src/js/tiles/core/multiWordGeoAreas/views/index.tsx
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
- src/js/tiles/core/wordSim/view.tsx
- src/js/views/global.tsx
Automatically derived cmp colors will be used if themes list of cmp colors have only one color and if size of required color set is provided. The single color from the list will be used as base color to calculate the set.
Issue #841
> Dynamic color palette

- src/css/index.less
- src/js/tiles/core/freqBar/messages.json
- src/js/tiles/core/freqBar/view.tsx
- src/js/tiles/core/freqComparison/view.tsx
- src/js/tiles/core/geoAreas/messages.json
- src/js/tiles/core/geoAreas/model.ts
- src/js/tiles/core/mergeCorpFreq/messages.json
- src/js/tiles/core/mergeCorpFreq/model.ts
- src/js/tiles/core/mergeCorpFreq/view.tsx
- src/js/tiles/core/multiWordGeoAreas/model.ts
- src/js/tiles/core/multiWordTimeDistrib/view.tsx
- src/js/views/global.tsx
- src/translations/messages.json
https://podpora.korpus.cz/issues/2024
> United tooltip labels

- package.json
- src/js/page/index.ts
> Detecting mobile device using cnc-tskit

- assets/next_grey.svg
- src/js/tiles/core/speeches/view.tsx
> Speeches support inactive next button in case nothing else is available

- src/js/server/freqdb/backends/korpusdb.ts
- implemented `getSourceDescription` method
- get rid of `deep-equal` package
Issue #868
> KorpusDB api improvements

- src/js/server/freqdb/backends/korpusdb.ts
- check for returned data type as KorpusDB returns code 200 even in case
of an error
- normalize API url in the config
> Add some tweaks to korpusdb adapter

- src/js/app.ts
- src/js/server/routes/main.ts
(but the new solution is still not perfect as it does
not always respect query type)
> Fix - do not use hardcoded srch. domains

- src/js/api/vendor/kontext/matchingDocs.ts
- src/js/page/tileLoader.ts
- src/js/tiles/core/matchingDocs/index.ts
also improve general message for sanity checks
> Sanity check for matching docs

- src/js/server/freqdb/backends/korpusdb.ts
- based on changes created by @mzimandl
- find all lemmas first, then individual freqs for all their forms
> Fix KorpusDB adapter

- install/migrate.py
- add dry run
- allow different target database (on the same server though)
> Improve migration script

- src/css/shared.less
- src/js/page/index.ts
- src/js/views/clarin/fcs1/explain.tsx
- src/js/views/common/corpusInfo.tsx
- src/js/views/common/index.tsx
- src/js/views/common/style.tsx
- src/js/views/layout/style.tsx
Groovepaper2.jpg background is working again
> Create path to static file directly in styles

- install/docker/server-build-and-run.sh
- src/js/server/actionLog/abstract.ts
- src/js/server/actionLog/common.ts
- src/js/server/routes/common.ts
- src/js/server/routes/index.ts
- src/js/server/routes/main.ts
- add missing 'action' arg
- detect (roughly) mobile client
- make the logging action asynchronous
> Improve action logging

- build.js
- docker-compose.yml
- test/tiles/core/html/model.ts
- remove less file alias
- fix unit test
- rename volume
> Misc fixes

- src/js/server/index.ts
... also rename session cookie
> Allow sessions with defined expiration time

- conf/server-schema.json
- src/js/conf/index.ts
- src/js/server/index.ts
- this should solve permanent/long-term sessions
> Customizable (static) session secret

- src/js/conf/index.ts
- src/js/server/freqdb/backends/korpusdb.ts
or to be more precise: offer an alternative data source as KorpusDB does not provide all the data we need
> Fix source info for KorpusDB freqdb backend

- src/js/tiles/core/concFilter/model.ts
> Fix uncontrollable lines multiplication

- src/js/api/abstract/syntacticColls.ts
- src/js/api/vendor/mquery/syntacticColls.ts
- src/js/models/tiles/syntacticColls.ts
- src/js/tiles/core/syntacticColls/config-schema.json
- src/js/tiles/core/syntacticColls/index.ts
- src/js/tiles/core/syntacticColls/model.ts
- src/js/tiles/core/syntacticColls/views.tsx
- table is the default view
- added `displayTypes` config
> Syntactic collocations improvements

- src/js/tiles/core/timeDistrib/common.ts
- src/js/tiles/core/timeDistrib/model.ts
(i.e. cannot wait for the last ID as it may arrive any time)
> Fix - chunks may arrive in different orders

- src/js/page/tile.ts
> Fix - backlink can be apparently a lot of things:

- src/js/api/vendor/mquery/timeDistrib.ts
(if `from` and `to` limits are defined)
> Fill in missing years with zero freq

- package-lock.json
- package.json
- src/js/conf/index.ts
- src/js/page/theme.ts
- src/js/server/freqdb/factory.ts
- src/js/tiles/core/timeDistrib/model.ts
- src/js/tiles/core/timeDistrib/view.tsx
1) Time distrib - fix unsupported multi-word queries 2) support for Frodo dictionary database
3) Time distrib - better presentation
> Fix time distrib tile plus extend theme properties:

- src/js/api/vendor/mquery/timeDistrib.ts
This reverts commit f803192b58e31d1b39001af4e4298594d7811d59.
> Revert "Fixing zerofill in timedist tile"

- src/js/api/vendor/mquery/timeDistrib.ts
(this is handled by server in a better way)
> Remove automatic filling of zero values

- src/js/app.ts
- src/js/models/actions.ts
- src/js/models/tiles.ts
- src/js/page/tile.ts
- src/js/tiles/core/freqBar/model.ts
- src/js/tiles/core/freqBar/view.tsx
- src/js/tiles/core/geoAreas/views/index.tsx
- src/js/tiles/core/timeDistrib/view.tsx
- src/js/views/common/index.tsx
- src/js/views/main.tsx
- test/models/tiles.ts
Get rid of dysfunctional SetTileRenderSize and use simple solution based on number of layout groups and window's inner height
> Freqbar upgrade

- src/js/api/vendor/mquery/timeDistrib.ts
- src/js/tiles/core/colloc/api.ts
- src/js/tiles/core/colloc/model.ts
- src/js/tiles/core/concordance/model.ts
- src/js/tiles/core/wordSim/model.ts
In such situation, affected tiles didn't register their request and the whole search failed with timeout
> Fix misc issues related to the "word not found" situation

- src/js/api/vendor/mquery/concordance/common.ts
- src/js/tiles/core/colloc/api.ts
- src/js/tiles/core/colloc/common.ts
- src/js/tiles/core/colloc/index.ts
- src/js/tiles/core/colloc/model.ts
- src/js/tiles/core/colloc/views.tsx
- src/js/tiles/core/concordance/model.ts
- src/js/tiles/core/concordance/style.tsx
- src/js/tiles/core/concordance/views.tsx
- src/js/views/common/index.tsx
- src/js/views/wordCloud/index.tsx
(this requires mquery to produce predefined interaction IDs)
> Fix/restore wordcloud --> concordance lines interaction

- src/js/views/style.tsx
in those cases, do not display the element at all
> Additional improvement of rev d33cee5278986793:
